export interface IMember{
    lastname : string, 
    firstname : string, 
    birthdate : string, 
    gender : string, 
    address1 : string, 
    address2 : string, 
    city : string, 
    postalcode : string, 
    phone : string, 
    email : string, 
    mobile : string, 
    emergencyContactLastname : string, 
    emergencyContactFirstname : string, 
    emergencyContactMobile : string, 
}